### ISSUE TITLE
Error: TCP connection localhost:cslistener didn't return valid data

### ISSUE THREAD

**Issue by yigitgokcu** [rvalitov/zabbix-php-fpm#24] opened 2020-02-03 09:47 UTC
Hello,

I'm getting an error like below; 

Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: '/bin/grep: write error: Broken pipe
{"data":[]}'

When I use debug;

Error: TCP connection localhost:cslistener didn't return valid data

I think, cause of this problem is PHP-FPM listening a TCP port. I'm not using unix socket on my hosts, but I change config to socket, everything is fine. How can I solve this issue? 

Thank you.

Best Regards.

**Comment by rvalitov** [comment] 2020-02-04 22:18
Hi! Thank you for reporting this. The script was tested and should work with TCP ports. The script finds the host and port and reports them in format `ip:port`, where `ip` is an IP address or `localhost`, and `port` is a number. In your case I see `cslistener` string instead of a port number. Does this string mean something to you? This problem happens only to 1 pool or do you have multiple pools with the same problem? Is the port reported the same for different pools by the script in debug mode? What is your OS? 
Please kindly answer to the questions above and I will help to fix this issue.

**Comment by rvalitov** [comment] 2020-02-04 22:39
I think I understand the cause of this problem - the OS reports the port as a name and not as a number as described here https://stackoverflow.com/questions/34032299/lsof-print-numeric-ports
I will fix that.

**Comment by yigitgokcu** [comment] 2020-02-05 08:11
Hi, I have one fpm pool but the problem happeens with multiple pools too. I'm using CentOS 7. I can't find any useful information about CSListener but I think, just that some company has used port 9000 for a firewall, and used it enough that it is reported as a "use of port 9000". 

`grep -e 9000 /etc/services`
`cslistener      9000/tcp                # CSlistener`
`cslistener      9000/udp                # CSlistener`

Yes, it looks like as you said.  Thank you!

**Comment by yigitgokcu** [comment] 2020-02-07 12:06
Hi! Yes, it works now, thank you!

**Comment by rvalitov** [comment] 2020-02-07 12:08
Great! Closed by #26

**Closed by rvalitov** 2020-02-07 12:08 UTC
Labels: bug, question
